CREATE TABLE `pricingQuotes` (
	`id` int AUTO_INCREMENT NOT NULL,
	`customerName` varchar(255),
	`customerEmail` varchar(320),
	`industry` varchar(255),
	`region` varchar(255),
	`tier` varchar(50) NOT NULL,
	`users` int NOT NULL,
	`suppliers` int NOT NULL,
	`protocols` int NOT NULL,
	`sites` int NOT NULL,
	`partnerTypes` int NOT NULL,
	`erpIntegration` int NOT NULL DEFAULT 0,
	`esrsSupport` int NOT NULL DEFAULT 0,
	`supportPremium` int NOT NULL DEFAULT 0,
	`basePrice` int NOT NULL,
	`usersPrice` int NOT NULL,
	`suppliersPrice` int NOT NULL,
	`protocolsPrice` int NOT NULL,
	`sitesPrice` int NOT NULL,
	`partnerTypesPrice` int NOT NULL,
	`erpIntegrationPrice` int NOT NULL,
	`esrsSupportPrice` int NOT NULL,
	`supportPremiumPrice` int NOT NULL,
	`annualPrice` int NOT NULL,
	`termYears` int NOT NULL DEFAULT 1,
	`totalPrice` int NOT NULL,
	`currency` varchar(10) NOT NULL DEFAULT 'USD',
	`status` varchar(50) NOT NULL DEFAULT 'draft',
	`notes` text,
	`stripeInvoiceId` varchar(255),
	`stripeInvoiceNumber` varchar(255),
	`stripePaymentLink` text,
	`createdBy` int,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `pricingQuotes_id` PRIMARY KEY(`id`)
);
